### ISSUE TITLE
PHPStorm + Postman

### ISSUE THREAD

**Issue by felipebool** [michelpl/palestras#1]
Segui os slides mas o XDebug não funcionava com o Postman no PHPStorm de jeito nenhum. Adicionei xdebug.remote_autostart=1 no meu php.ini e tudo funcionou perfeitamente.

Você poderia, ou adicionar isto aos slides, ou indicar que caso alguém não consiga fazer funcionar da maneira da palestra, é possível tentar usar também esta opção. 

:v:

**Comment by michelpl** [comment]
Adicionei um documento com todas as linhas que precisam ser adicionadas ao php.ini
